Message on making unbreakable: true
Message on enchant cancel: true
Message on enchant: false

Also repair: true

Anvil enchant delay sec: 5
Anvil enchant cost: 3

Hide Unbreakable: false

#
# If not set, worldlists default to ALL
# Enchanting worldlist:
# - world
# Lore unbreakable string: Unbreakable

# Below is added to Unbreakable enchanted items
# Enchant lore: 
# - line 1
# - line 2
# - line 3
# - line 4

Protect armor: true
Protect tools: true
Protect weapons: true

#
# Following only effective if one or more of 'Protect *' set true
#

# Auto fix worldlist:
# - world

# No permissions check if this turned on
Unbreakable on spawn: false
# Permissions checked for these three
Unbreakable on pickup: false
# Only effective for tools and weapons, may not catch armor
Unbreakable on hold: false
# Checks entire player inventory
Unbreakable on join: false
# remove Unbreakable when entering world not in 'Auto fix worldlist', if it's been set
Breakable on leave world: false


